`timescale 1ns / 1ps

// ============================================================
// Parallel Accelerator with DDR result transmitter
// - 4 lanes consume two 32-bit input streams (A and B) in parallel.
// - Per lane result: A + B.
// - Each lane is a combinational adder; there are no pipeline stages.
// - The APB wrapper registers each result so software can read it later.
// - After START, the four results are sent as a 32-bit DDR stream:
//   lane 0 on the first rising edge, lane 1 on the first falling edge,
//   lane 2 on the next rising edge and lane 3 on the next falling edge.
// - APB wrapper is mapped by soc_top at 0x4000_3000 - 0x4000_3FFF.
// ============================================================

// DDR serializer for an AMD/Xilinx FPGA.  The ODDR instances emit D1 at the
// rising edge and D2 at the falling edge of clk.
module ddr_result_serializer #(
    parameter DATA_WIDTH = 32
)(
    input  wire                  clk,
    input  wire                  rst_n,
    input  wire                  load,
    input  wire [DATA_WIDTH-1:0] data_rise_0,
    input  wire [DATA_WIDTH-1:0] data_fall_0,
    input  wire [DATA_WIDTH-1:0] data_rise_1,
    input  wire [DATA_WIDTH-1:0] data_fall_1,
    output wire [DATA_WIDTH-1:0] ddr_data,
    output wire                  ddr_clk_out,
    output reg                   ddr_valid,
    output reg                   ddr_done,
    output wire                  ddr_ready
);

    localparam PHASE_IDLE   = 2'd0;
    localparam PHASE_SEND_0 = 2'd1;
    localparam PHASE_SEND_1 = 2'd2;
    localparam PHASE_DONE   = 2'd3;

    reg [1:0] phase;
    reg [DATA_WIDTH-1:0] rise_word;
    reg [DATA_WIDTH-1:0] fall_word;

    assign ddr_ready = (phase == PHASE_IDLE);

    genvar bit_index;
    generate
        for (bit_index = 0; bit_index < DATA_WIDTH; bit_index = bit_index + 1) begin : gen_oddr
            ODDR #(
                .DDR_CLK_EDGE ("SAME_EDGE"),
                .INIT         (1'b0),
                .SRTYPE       ("SYNC")
            ) u_oddr (
                .Q  (ddr_data[bit_index]),
                .C  (clk),
                .CE (1'b1),
                .D1 (rise_word[bit_index]),
                .D2 (fall_word[bit_index]),
                .R  (~rst_n),
                .S  (1'b0)
            );
        end
    endgenerate

    // Forward the DDR sampling clock to the receiver.  D1=1 and D2=0
    // reproduce clk at the output.  A 90-degree phase shift, if required by
    // the physical receiver, must be generated by an MMCM/PLL.
    ODDR #(
        .DDR_CLK_EDGE ("SAME_EDGE"),
        .INIT         (1'b0),
        .SRTYPE       ("SYNC")
    ) u_oddr_clk (
        .Q  (ddr_clk_out),
        .C  (clk),
        .CE (1'b1),
        .D1 (1'b1),
        .D2 (1'b0),
        .R  (~rst_n),
        .S  (1'b0)
    );

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            phase     <= PHASE_IDLE;
            rise_word <= {DATA_WIDTH{1'b0}};
            fall_word <= {DATA_WIDTH{1'b0}};
            ddr_valid <= 1'b0;
            ddr_done  <= 1'b0;
        end else begin
            ddr_done <= 1'b0;

            case (phase)
                PHASE_IDLE: begin
                    if (load) begin
                        rise_word <= data_rise_0;
                        fall_word <= data_fall_0;
                        phase     <= PHASE_SEND_0;
                    end
                end

                // ODDR samples the first pair above at this edge.  Prepare
                // the next pair for the following rising/falling edge pair.
                PHASE_SEND_0: begin
                    rise_word <= data_rise_1;
                    fall_word <= data_fall_1;
                    ddr_valid <= 1'b1;
                    phase     <= PHASE_SEND_1;
                end

                // The second pair is now on the DDR pins.  Keep valid high
                // through the following falling edge so the receiver can
                // sample data_fall_1.
                PHASE_SEND_1: begin
                    phase <= PHASE_DONE;
                end

                default: begin
                    ddr_valid <= 1'b0;
                    ddr_done  <= 1'b1;
                    phase     <= PHASE_IDLE;
                end
            endcase
        end
    end

endmodule

module parallel_lane (
    input  wire        in_valid,
    output wire        in_ready,
    input  wire [31:0] a,
    input  wire [31:0] b,

    output wire        out_valid,
    input  wire        out_ready,
    output wire [31:0] result_out
);

    assign in_ready   = out_ready;
    assign out_valid  = in_valid;
    assign result_out = a + b;

endmodule


module parallel_core #(
    parameter NUM_LANES = 4
)(
    input  wire [NUM_LANES-1:0]         in_valid,
    output wire [NUM_LANES-1:0]         in_ready,
    input  wire [(NUM_LANES*32)-1:0]    a_flat,
    input  wire [(NUM_LANES*32)-1:0]    b_flat,

    output wire [NUM_LANES-1:0]         out_valid,
    input  wire [NUM_LANES-1:0]         out_ready,
    output wire [(NUM_LANES*32)-1:0]    result_flat
);

    genvar i;
    generate
        for (i = 0; i < NUM_LANES; i = i + 1) begin : gen_lanes
            parallel_lane u_lane (
                .in_valid   (in_valid[i]),
                .in_ready   (in_ready[i]),
                .a          (a_flat[(i*32) +: 32]),
                .b          (b_flat[(i*32) +: 32]),
                .out_valid  (out_valid[i]),
                .out_ready  (out_ready[i]),
                .result_out (result_flat[(i*32) +: 32])
            );
        end
    endgenerate

endmodule


module parallel #(
    parameter NUM_LANES = 4
)(
    input  wire        clk,
    input  wire        rst_n,

    input  wire [31:0] PADDR,
    input  wire        PWRITE,
    input  wire        PSEL,
    input  wire        PENABLE,
    input  wire [31:0] PWDATA,
    output wire [31:0] PRDATA,
    output wire        PREADY,
    output wire        PSLVERR,

    output wire [31:0] result_out,
    output wire        result_valid,

    // DDR output stream.  Four lane results are serialized over two clocks.
    output wire [31:0] ddr_data,
    output wire        ddr_clk_out,
    output wire        ddr_valid,
    output wire        ddr_done
);

    localparam [7:0] REG_CTRL_STATUS = 8'h00;
    localparam [7:0] REG_A_BASE      = 8'h10;
    localparam [7:0] REG_B_BASE      = 8'h20;
    localparam [7:0] REG_RESULT_BASE = 8'h30;

    reg  [31:0] reg_a      [0:NUM_LANES-1];
    reg  [31:0] reg_b      [0:NUM_LANES-1];
    reg  [31:0] reg_result [0:NUM_LANES-1];
    reg  [NUM_LANES-1:0] start_pending;
    reg  [NUM_LANES-1:0] result_valid_reg;

    wire [NUM_LANES-1:0] core_in_ready;
    wire [NUM_LANES-1:0] core_out_valid;
    wire [NUM_LANES-1:0] fire_start;
    wire [(NUM_LANES*32)-1:0] a_flat;
    wire [(NUM_LANES*32)-1:0] b_flat;
    wire [(NUM_LANES*32)-1:0] result_flat;
    wire ddr_ready;

    reg        pready_reg;
    reg [31:0] prdata_reg;
    reg        pslverr_reg;

    assign PREADY  = pready_reg;
    assign PRDATA  = prdata_reg;
    assign PSLVERR = pslverr_reg;

    assign fire_start   = start_pending & core_in_ready & {NUM_LANES{ddr_ready}};
    assign result_out   = reg_result[0];
    assign result_valid = |result_valid_reg;

    genvar i;
    generate
        for (i = 0; i < NUM_LANES; i = i + 1) begin : gen_pack
            assign a_flat[(i*32) +: 32] = reg_a[i];
            assign b_flat[(i*32) +: 32] = reg_b[i];
        end
    endgenerate

    parallel_core #(
        .NUM_LANES(NUM_LANES)
    ) u_core (
        .in_valid    (fire_start),
        .in_ready    (core_in_ready),
        .a_flat      (a_flat),
        .b_flat      (b_flat),
        .out_valid   (core_out_valid),
        .out_ready   ({NUM_LANES{1'b1}}),
        .result_flat (result_flat)
    );

    // NUM_LANES is four in the current SoC.  The serializer makes the data
    // path visible at both edges of clk without changing the APB register map.
    ddr_result_serializer #(
        .DATA_WIDTH (32)
    ) u_ddr_result_serializer (
        .clk         (clk),
        .rst_n       (rst_n),
        .load        (|fire_start),
        .data_rise_0 (result_flat[31:0]),
        .data_fall_0 (result_flat[63:32]),
        .data_rise_1 (result_flat[95:64]),
        .data_fall_1 (result_flat[127:96]),
        .ddr_data    (ddr_data),
        .ddr_clk_out (ddr_clk_out),
        .ddr_valid   (ddr_valid),
        .ddr_done    (ddr_done),
        .ddr_ready   (ddr_ready)
    );

    integer lane;
    reg [7:0] offset;
    reg [1:0] addr_lane;

    always @(*) begin
        offset    = PADDR[7:0];
        addr_lane = PADDR[3:2];
    end

    always @(posedge clk) begin
        if (!rst_n) begin
            pready_reg       <= 1'b0;
            prdata_reg       <= 32'h0;
            pslverr_reg      <= 1'b0;
            start_pending    <= {NUM_LANES{1'b0}};
            result_valid_reg <= {NUM_LANES{1'b0}};

            for (lane = 0; lane < NUM_LANES; lane = lane + 1) begin
                reg_a[lane]      <= 32'h0;
                reg_b[lane]      <= 32'h0;
                reg_result[lane] <= 32'h0;
            end
        end else begin
            pready_reg    <= 1'b0;
            pslverr_reg   <= 1'b0;
            start_pending <= start_pending & ~fire_start;

            for (lane = 0; lane < NUM_LANES; lane = lane + 1) begin
                if (core_out_valid[lane]) begin
                    reg_result[lane]      <= result_flat[(lane*32) +: 32];
                    result_valid_reg[lane] <= 1'b1;
                end
            end

            if (PSEL && PENABLE && !pready_reg) begin
                pready_reg <= 1'b1;

                if (PWRITE) begin
                    case (offset)
                        REG_CTRL_STATUS: begin
                            if (PWDATA[0])
                                start_pending <= start_pending |
                                    ((|PWDATA[NUM_LANES+7:8]) ? PWDATA[NUM_LANES+7:8] : {NUM_LANES{1'b1}});
                            if (PWDATA[1])
                                result_valid_reg <= result_valid_reg &
                                    ~((|PWDATA[NUM_LANES+15:16]) ? PWDATA[NUM_LANES+15:16] : {NUM_LANES{1'b1}});
                        end
                        REG_A_BASE + 8'h00,
                        REG_A_BASE + 8'h04,
                        REG_A_BASE + 8'h08,
                        REG_A_BASE + 8'h0c: reg_a[addr_lane] <= PWDATA;
                        REG_B_BASE + 8'h00,
                        REG_B_BASE + 8'h04,
                        REG_B_BASE + 8'h08,
                        REG_B_BASE + 8'h0c: reg_b[addr_lane] <= PWDATA;
                        default: pslverr_reg <= 1'b1;
                    endcase
                end else begin
                    case (offset)
                        REG_CTRL_STATUS: prdata_reg <= {
                            8'h00,
                            4'h0,
                            result_valid_reg,
                            4'h0,
                            start_pending,
                            4'h0,
                            core_in_ready
                        };
                        REG_A_BASE + 8'h00,
                        REG_A_BASE + 8'h04,
                        REG_A_BASE + 8'h08,
                        REG_A_BASE + 8'h0c: prdata_reg <= reg_a[addr_lane];
                        REG_B_BASE + 8'h00,
                        REG_B_BASE + 8'h04,
                        REG_B_BASE + 8'h08,
                        REG_B_BASE + 8'h0c: prdata_reg <= reg_b[addr_lane];
                        REG_RESULT_BASE + 8'h00,
                        REG_RESULT_BASE + 8'h04,
                        REG_RESULT_BASE + 8'h08,
                        REG_RESULT_BASE + 8'h0c: begin
                            prdata_reg <= reg_result[addr_lane];
                            result_valid_reg[addr_lane] <= 1'b0;
                        end
                        default: begin
                            prdata_reg  <= 32'hDEAD_BEEF;
                            pslverr_reg <= 1'b1;
                        end
                    endcase
                end
            end
        end
    end

endmodule
